name: Publish to Image Registry

on:
  workflow_dispatch:

jobs:
  release_x86:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      arch: amd64
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}
    permissions:
      id-token: write
      contents: read
    steps:
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.AWS_ECR_PREFIX }}/supabase/studio
          tags: |
            type=raw,value=latest

      - name: Setup Chalk
        uses: crashappsec/setup-chalk-action@main
        with:
          connect: true

      - name: Assume AWS Role
        id: role
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 #v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GithubDeploy

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 #v2.0.1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - uses: docker/setup-buildx-action@v2

      - id: build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: '{{defaultContext}}'
          file: apps/studio/Dockerfile
          target: production
          platforms: linux/${{ env.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
